
title: Learnings
email:
description: Notes about computer science subjects made during my time as an engineering student and then as a software engineer

github_username: abhijithmadhav
minimal_mistakes_skin: default
search: true

repository: abhijithmadhav/abhijithmadhav.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kolkata

include:
  - _pages

show_drafts: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

author:
  name   : "Abhijith Madhav"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software Engineer"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abhijithmadhav"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/abhijith-madhav/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://abhijithmadhav.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abhijithmadhav"

collections_dir: collections
collections:
  distributed-systems:
    output: true
    permalink: /:collection/:path/
  system-design:
    output: true
    permalink: /:collection/:path/
  kafka:
    output: true
    permalink: /:collection/:path/
  operating-system:
    output: true
    permalink: /:collection/:path/
  databases:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: false
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      toc: true
      toc_sticky: true

  # experiences
  - scope:
      path: ""
      type: experiences
    values:
      layout: single
      author_profile: false
      toc: true
      toc_sticky: true

  # system-design
  - scope:
      path: ""
      type: system-design
    values:
      layout: single
      author_profile: false
      toc: true
      toc_sticky: true

  # databases
  - scope:
      path: ""
      type: databases
    values:
      layout: single
      author_profile: false
      toc: true
      toc_sticky: true

  # distributed-systems
  - scope:
      path: ""
      type: distributed-systems
    values:
      layout: single
      author_profile: false
      toc: true
      toc_sticky: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
