
title: Another SE
email:
description: >- # this means to ignore newlines until "baseurl:"
  Documentation of software engineering journey
twitter_username: madhavabhijith
github_username: abhijithmadhav
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

author:
  name   : "Abhijith Madhav"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "TODO"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://abhijithmadhav.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abhijithmadhav"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://abhijithmadhav.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abhijithmadhav"

collections_dir: my_collections
collections:
  operating-system:
    output: true
    permalink: /:collection/:path/
  distributed-systems:
    output: true
    permalink: /:collection/:path/
  system-design:
    output: true
    permalink: /:collection/:path/
  experiences:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
